from .admin.admin import admin
from .admin.task_management import admin_tasks
from .admin.news_management import admin_news
from .api import api
from .authify import auth
from .user import user
from .profile import profile
from .gpt import gpt
from .summary import summary
from .post import post
from .ide import ide